// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOvIR0gs8iEmnh3KZCaO0FcQ3Nt_wu28Y',
    appId: '1:377767950216:android:cc29786680d548658cac3d',
    messagingSenderId: '377767950216',
    projectId: 'dars-71',
    databaseURL: 'https://dars-71-default-rtdb.firebaseio.com',
    storageBucket: 'dars-71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2ouAdyjKDumB372stWM8SDQpP9fchNgE',
    appId: '1:377767950216:ios:142e3d60be8759218cac3d',
    messagingSenderId: '377767950216',
    projectId: 'dars-71',
    databaseURL: 'https://dars-71-default-rtdb.firebaseio.com',
    storageBucket: 'dars-71.appspot.com',
    iosClientId: '377767950216-j698k3jp44rhs2lstpcusdtl8fldierg.apps.googleusercontent.com',
    iosBundleId: 'com.example.dars74',
  );
}
